spring.application.name=blog-api

spring.jpa.hibernate.ddl-auto=update

#Para desenvolvimento H2, mas eu tô usando variáveis de ambiente para acessar banco mysql
spring.datasource.url=jdbc:h2:mem:blodraft
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.show-sql=true
